import type {
  User,
  Farm,
  Batch,
  Transfer,
  LabReport,
  TransportLog,
  QRRecord,
  SupplyChainEvent,
  DashboardStats,
  Product,
  Order,
  ConsumerProfile,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Arjun Patel",
    email: "arjun@sattva.io",
    role: "farmer",
    walletAddress: "0x7a3B...f91E",
    verifiedStatus: true,
    createdAt: "2025-01-15T08:00:00Z",
    avatar: "/avatars/farmer.jpg",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya@sattva.io",
    role: "manufacturer",
    walletAddress: "0x8c4D...a23F",
    verifiedStatus: true,
    createdAt: "2025-02-01T10:00:00Z",
  },
  {
    id: "u3",
    name: "Ravi Kumar",
    email: "ravi@sattva.io",
    role: "consumer",
    verifiedStatus: false,
    createdAt: "2025-03-10T12:00:00Z",
  },
]

export const mockFarms: Farm[] = [
  {
    id: "f1",
    farmerId: "u1",
    farmName: "Patel Organic Farm",
    geoLocation: { lat: 23.2599, lng: 77.4126, address: "Bhopal, Madhya Pradesh, India" },
  },
  {
    id: "f2",
    farmerId: "u1",
    farmName: "Himalayan Herb Gardens",
    geoLocation: { lat: 30.7333, lng: 79.0667, address: "Uttarakhand, India" },
  },
]

export const mockBatches: Batch[] = [
  {
    id: "b1",
    herbName: "Ashwagandha",
    quantity: 500,
    unit: "kg",
    harvestDate: "2025-09-15",
    aiQualityScore: 94.5,
    blockchainHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
    status: "qr_generated",
    createdBy: "u1",
    farmId: "f1",
  },
  {
    id: "b2",
    herbName: "Tulsi",
    quantity: 300,
    unit: "kg",
    harvestDate: "2025-10-01",
    aiQualityScore: 91.2,
    blockchainHash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
    status: "lab_tested",
    createdBy: "u1",
    farmId: "f1",
  },
  {
    id: "b3",
    herbName: "Brahmi",
    quantity: 200,
    unit: "kg",
    harvestDate: "2025-10-10",
    aiQualityScore: 88.7,
    blockchainHash: "0xfedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
    status: "verified",
    createdBy: "u1",
    farmId: "f2",
  },
  {
    id: "b4",
    herbName: "Turmeric",
    quantity: 750,
    unit: "kg",
    harvestDate: "2025-08-20",
    aiQualityScore: 96.1,
    blockchainHash: "0x9876543210abcdef9876543210abcdef9876543210abcdef9876543210abcdef",
    status: "delivered",
    createdBy: "u1",
    farmId: "f1",
  },
  {
    id: "b5",
    herbName: "Neem",
    quantity: 400,
    unit: "kg",
    harvestDate: "2025-11-01",
    aiQualityScore: 89.3,
    blockchainHash: "0xaabbccdd11223344aabbccdd11223344aabbccdd11223344aabbccdd11223344",
    status: "harvested",
    createdBy: "u1",
    farmId: "f2",
  },
  {
    id: "b6",
    herbName: "Shatavari",
    quantity: 150,
    unit: "kg",
    harvestDate: "2025-10-20",
    aiQualityScore: 92.8,
    blockchainHash: "0x5566778899aabbcc5566778899aabbcc5566778899aabbcc5566778899aabbcc",
    status: "in_transit",
    createdBy: "u1",
    farmId: "f1",
  },
]

export const mockTransfers: Transfer[] = [
  {
    id: "t1",
    batchId: "b1",
    fromUserId: "u1",
    toUserId: "u2",
    timestamp: "2025-09-20T14:00:00Z",
    fromUserName: "Arjun Patel",
    toUserName: "Priya Sharma",
  },
  {
    id: "t2",
    batchId: "b4",
    fromUserId: "u1",
    toUserId: "u2",
    timestamp: "2025-09-01T09:00:00Z",
    fromUserName: "Arjun Patel",
    toUserName: "Priya Sharma",
  },
  {
    id: "t3",
    batchId: "b2",
    fromUserId: "u1",
    toUserId: "u2",
    timestamp: "2025-10-05T11:00:00Z",
    fromUserName: "Arjun Patel",
    toUserName: "Priya Sharma",
  },
]

export const mockLabReports: LabReport[] = [
  {
    id: "l1",
    batchId: "b1",
    ipfsHash: "QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco",
    verificationStatus: "verified",
    testDate: "2025-09-25",
    results: { purity: 98.5, contaminants: false, activeCompounds: 87, grade: "A+" },
  },
  {
    id: "l2",
    batchId: "b2",
    ipfsHash: "QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG",
    verificationStatus: "verified",
    testDate: "2025-10-08",
    results: { purity: 95.2, contaminants: false, activeCompounds: 82, grade: "A" },
  },
  {
    id: "l3",
    batchId: "b4",
    ipfsHash: "QmZ4tDuvesekSs4qM5DYaAlYPEbz2NShVDVGhn2ogcVJ42",
    verificationStatus: "verified",
    testDate: "2025-09-05",
    results: { purity: 99.1, contaminants: false, activeCompounds: 94, grade: "A+" },
  },
]

export const mockTransportLogs: TransportLog[] = [
  { id: "tl1", batchId: "b1", temperature: 22.5, humidity: 45, timestamp: "2025-09-20T15:00:00Z", location: "Bhopal Warehouse" },
  { id: "tl2", batchId: "b1", temperature: 23.1, humidity: 42, timestamp: "2025-09-21T08:00:00Z", location: "In Transit - NH44" },
  { id: "tl3", batchId: "b1", temperature: 21.8, humidity: 48, timestamp: "2025-09-22T12:00:00Z", location: "Mumbai Processing Center" },
  { id: "tl4", batchId: "b4", temperature: 24.0, humidity: 40, timestamp: "2025-09-01T10:00:00Z", location: "Bhopal Warehouse" },
  { id: "tl5", batchId: "b4", temperature: 23.5, humidity: 43, timestamp: "2025-09-02T16:00:00Z", location: "Pune Distribution Hub" },
]

export const mockQRRecords: QRRecord[] = [
  { id: "qr1", batchId: "b1", qrCodeURL: "https://sattva.io/verify/b1", generatedAt: "2025-09-28T10:00:00Z" },
  { id: "qr2", batchId: "b4", qrCodeURL: "https://sattva.io/verify/b4", generatedAt: "2025-09-10T10:00:00Z" },
]

export const mockSupplyChainEvents: SupplyChainEvent[] = [
  {
    id: "e1", batchId: "b1", type: "harvest",
    title: "Herb Harvested", description: "Ashwagandha harvested at Patel Organic Farm, Bhopal",
    timestamp: "2025-09-15T06:00:00Z", actor: "Arjun Patel", verified: true,
  },
  {
    id: "e2", batchId: "b1", type: "verification",
    title: "AI Quality Verified", description: "AI analysis scored 94.5% quality rating",
    timestamp: "2025-09-16T10:00:00Z", actor: "Sattva AI", verified: true,
  },
  {
    id: "e3", batchId: "b1", type: "transfer",
    title: "Transferred to Manufacturer", description: "Batch transferred to Priya Sharma for processing",
    timestamp: "2025-09-20T14:00:00Z", actor: "Arjun Patel", verified: true,
  },
  {
    id: "e4", batchId: "b1", type: "lab_test",
    title: "Lab Testing Complete", description: "Grade A+ - 98.5% purity, no contaminants detected",
    timestamp: "2025-09-25T16:00:00Z", actor: "Sattva Labs", verified: true,
  },
  {
    id: "e5", batchId: "b1", type: "processing",
    title: "Processing Complete", description: "Herb processed, packaged, and sealed",
    timestamp: "2025-09-27T09:00:00Z", actor: "Priya Sharma", verified: true,
  },
  {
    id: "e6", batchId: "b1", type: "qr_generated",
    title: "QR Code Generated", description: "Product QR code generated for consumer verification",
    timestamp: "2025-09-28T10:00:00Z", actor: "Sattva System", verified: true,
  },
]

export const mockFarmerStats: DashboardStats = {
  totalBatches: 6,
  activeBatches: 4,
  verifiedBatches: 3,
  qualityScore: 92.1,
  totalTransfers: 3,
  pendingLabReports: 1,
}

export const mockManufacturerStats: DashboardStats = {
  totalBatches: 12,
  activeBatches: 5,
  verifiedBatches: 10,
  qualityScore: 95.4,
  totalTransfers: 8,
  pendingLabReports: 2,
}

export const monthlyBatchData = [
  { month: "Jun", batches: 8, verified: 6 },
  { month: "Jul", batches: 12, verified: 10 },
  { month: "Aug", batches: 15, verified: 13 },
  { month: "Sep", batches: 18, verified: 15 },
  { month: "Oct", batches: 22, verified: 19 },
  { month: "Nov", batches: 14, verified: 12 },
]

export const herbDistribution = [
  { herb: "Ashwagandha", percentage: 28, batches: 45 },
  { herb: "Tulsi", percentage: 22, batches: 35 },
  { herb: "Turmeric", percentage: 20, batches: 32 },
  { herb: "Brahmi", percentage: 16, batches: 26 },
  { herb: "Neem", percentage: 14, batches: 22 },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    herbName: "Ashwagandha Root Powder",
    description: "Premium organic Ashwagandha root powder sourced from Bhopal, MP. Known for its adaptogenic properties that help the body manage stress and promote vitality. Grown without pesticides in mineral-rich soil.",
    price: 899,
    currency: "INR",
    batchId: "b1",
    farmId: "f1",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Madhya Pradesh",
    verified: true,
    aiQualityScore: 94.5,
    blockchainHash: "0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890",
    labGrade: "A+",
    weight: "250g",
    inStock: true,
  },
  {
    id: "p2",
    herbName: "Holy Basil (Tulsi) Leaves",
    description: "Hand-picked Tulsi leaves dried at optimal temperatures to preserve essential oils. Revered in Ayurveda for respiratory wellness, immunity support, and mental clarity.",
    price: 549,
    currency: "INR",
    batchId: "b2",
    farmId: "f1",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Madhya Pradesh",
    verified: true,
    aiQualityScore: 91.2,
    blockchainHash: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
    labGrade: "A",
    weight: "100g",
    inStock: true,
  },
  {
    id: "p3",
    herbName: "Brahmi Leaf Extract",
    description: "Pure Brahmi extract from the foothills of the Himalayas. Traditionally used to enhance cognitive function, memory, and focus. Cold-processed to retain maximum potency.",
    price: 1199,
    currency: "INR",
    batchId: "b3",
    farmId: "f2",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Uttarakhand",
    verified: true,
    aiQualityScore: 88.7,
    blockchainHash: "0xfedcba0987654321fedcba0987654321fedcba0987654321fedcba0987654321",
    labGrade: "A",
    weight: "200ml",
    inStock: true,
  },
  {
    id: "p4",
    herbName: "Golden Turmeric Powder",
    description: "High-curcumin turmeric grown in rich alluvial soil. Lab-verified for exceptional purity and potency. A cornerstone of Ayurvedic wellness for its anti-inflammatory properties.",
    price: 699,
    currency: "INR",
    batchId: "b4",
    farmId: "f1",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Madhya Pradesh",
    verified: true,
    aiQualityScore: 96.1,
    blockchainHash: "0x9876543210abcdef9876543210abcdef9876543210abcdef9876543210abcdef",
    labGrade: "A+",
    weight: "500g",
    inStock: true,
  },
  {
    id: "p5",
    herbName: "Neem Leaf Capsules",
    description: "Concentrated Neem leaf powder in vegetarian capsules. Known for blood purification, skin health, and natural detoxification. Sustainably harvested from Himalayan gardens.",
    price: 449,
    currency: "INR",
    batchId: "b5",
    farmId: "f2",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Uttarakhand",
    verified: false,
    aiQualityScore: 89.3,
    blockchainHash: "0xaabbccdd11223344aabbccdd11223344aabbccdd11223344aabbccdd11223344",
    labGrade: "B+",
    weight: "60 caps",
    inStock: true,
  },
  {
    id: "p6",
    herbName: "Shatavari Root Powder",
    description: "Wildcrafted Shatavari root, slow-dried and ground to a fine powder. Celebrated in Ayurveda for hormonal balance, reproductive health, and nourishing vitality.",
    price: 999,
    currency: "INR",
    batchId: "b6",
    farmId: "f1",
    farmerName: "Arjun Patel",
    manufacturerName: "Priya Sharma",
    region: "Madhya Pradesh",
    verified: true,
    aiQualityScore: 92.8,
    blockchainHash: "0x5566778899aabbcc5566778899aabbcc5566778899aabbcc5566778899aabbcc",
    labGrade: "A",
    weight: "300g",
    inStock: false,
  },
]

export const mockOrders: Order[] = [
  {
    id: "ord1",
    consumerId: "u3",
    productId: "p1",
    productName: "Ashwagandha Root Powder",
    quantity: 2,
    totalPrice: 1798,
    status: "delivered",
    createdAt: "2025-12-10T09:00:00Z",
    deliveryAddress: "42 MG Road, Bangalore, Karnataka 560001",
    batchId: "b1",
  },
  {
    id: "ord2",
    consumerId: "u3",
    productId: "p4",
    productName: "Golden Turmeric Powder",
    quantity: 1,
    totalPrice: 699,
    status: "delivered",
    createdAt: "2025-12-22T14:00:00Z",
    deliveryAddress: "42 MG Road, Bangalore, Karnataka 560001",
    batchId: "b4",
  },
  {
    id: "ord3",
    consumerId: "u3",
    productId: "p2",
    productName: "Holy Basil (Tulsi) Leaves",
    quantity: 3,
    totalPrice: 1647,
    status: "shipped",
    createdAt: "2026-01-15T11:00:00Z",
    deliveryAddress: "42 MG Road, Bangalore, Karnataka 560001",
    batchId: "b2",
  },
  {
    id: "ord4",
    consumerId: "u3",
    productId: "p3",
    productName: "Brahmi Leaf Extract",
    quantity: 1,
    totalPrice: 1199,
    status: "processing",
    createdAt: "2026-02-01T08:00:00Z",
    deliveryAddress: "42 MG Road, Bangalore, Karnataka 560001",
    batchId: "b3",
  },
]

export const mockConsumerProfile: ConsumerProfile = {
  userId: "u3",
  name: "Ravi Kumar",
  email: "ravi@sattva.io",
  address: "42 MG Road, Bangalore, Karnataka 560001",
  phone: "+91 98765 43210",
  preferences: ["Ashwagandha", "Turmeric", "Brahmi"],
  walletAddress: "0x4e2F...c89A",
}
